# Generated by Django 4.0.3 on 2022-04-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('inpx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagealias',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='library.language', verbose_name='Language'),
        ),
        migrations.AddConstraint(
            model_name='inp',
            constraint=models.CheckConstraint(check=models.Q(('file__gt', '')), name='inpx_inp.file_required'),
        ),
        migrations.AddConstraint(
            model_name='inp',
            constraint=models.CheckConstraint(check=models.Q(('mdhash__gt', '')), name='inpx_inp.mdhash_required'),
        ),
        migrations.AddField(
            model_name='genrealias',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='library.genre', verbose_name='Gennre'),
        ),
    ]
