# Generated by Django 5.1.5 on 2025-02-04 09:26

import datetime

from django.db import migrations, models


def add_statistic_data(apps, schema_editor):
    Statistic = apps.get_model('inpx', 'Statistic')

    fields = (
        'books_parsed',
        'parse_errors',
        'inps_created',
        'inps_updated',
        'series_created',
        'authors_created',
        'books_created',
        'books_updated',
        'time_spent_parse',
        'time_spent_update',
        'file',
    )

    statistic = list(Statistic.objects.all())

    for index, record in enumerate(statistic):
        if not index:
            for item in ('books_parsed', 'parse_errors', 'inps_created', 'inps_updated',
                         'series_created', 'authors_created', 'books_created', 'books_updated',):
                setattr(record, item, 0)
            for item in ('time_spent_parse', 'time_spent_update',):
                setattr(record, item, datetime.timedelta(seconds=0))
        else:
            for item in ('books_parsed', 'parse_errors', 'inps_created', 'inps_updated', 'books_updated',):
                setattr(record, item, 0)
            for item in ('time_spent_parse', 'time_spent_update',):
                setattr(record, item, datetime.timedelta(seconds=0))

            record.series_created = record.series_database - statistic[index - 1].series_database
            record.authors_created = record.authors_database - statistic[index - 1].authors_database
            record.books_created = record.books_database - statistic[index - 1].books_database

        record.file = ''

    Statistic.objects.bulk_update(statistic, fields)


def remove_statistic_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inpx', '0006_initial_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='authors_created',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Authors created'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='books_created',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Books created'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='books_parsed',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Books parsed'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='books_updated',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Books updated'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='file',
            field=models.CharField(blank=True, editable=False, max_length=4096, null=True, verbose_name='INPX file'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='inps_created',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='INPS created'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='inps_updated',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='INPS updated'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='parse_errors',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Parse errors'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='series_created',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Series creaated'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='time_spent_parse',
            field=models.DurationField(blank=True, editable=False, null=True, verbose_name='Parse time spend'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='time_spent_update',
            field=models.DurationField(blank=True, editable=False, null=True, verbose_name='Update time spend'),
        ),
        migrations.RunPython(
            add_statistic_data,
            remove_statistic_data,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='authors_created',
            field=models.PositiveIntegerField(blank=True, editable=False, verbose_name='Authors created'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='books_created',
            field=models.PositiveIntegerField(blank=True, editable=False, verbose_name='Books created'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='books_parsed',
            field=models.PositiveIntegerField(blank=True, editable=False, verbose_name='Books parsed'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='books_updated',
            field=models.PositiveIntegerField(blank=True, editable=False, verbose_name='Books updated'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='file',
            field=models.CharField(blank=True, editable=False, max_length=4096, verbose_name='INPX file'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='inps_created',
            field=models.PositiveIntegerField(blank=True, editable=False, verbose_name='INPS created'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='inps_updated',
            field=models.PositiveIntegerField(blank=True, editable=False, verbose_name='INPS updated'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='parse_errors',
            field=models.PositiveIntegerField(blank=True, editable=False, verbose_name='Parse errors'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='series_created',
            field=models.PositiveIntegerField(blank=True, editable=False, verbose_name='Series creaated'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='time_spent_parse',
            field=models.DurationField(blank=True, editable=False, verbose_name='Parse time spend'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='time_spent_update',
            field=models.DurationField(blank=True, editable=False, verbose_name='Update time spend'),
        ),
    ]
